name: newtify
version: 1.2.3
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http_server: ^0.9.8+1
  utf: ^0.9.0+5
  benchmark_harness: ">1.0.0"
  json_annotation: any
  random_string: ^0.0.2
  vm_service_lib: any
  json_serializable: any


dev_dependencies:
  build_runner: ^1.0.0
